### PR TITLE
newline "\n" should be escaped

### PR DESCRIPTION
**Pull request by milkwine**

### CODE REVIEW

**Comment by gravityblast** [comment]
thank you @sawater , can you please update a test to check this thing please?

**Comment by milkwine** [comment]
hi @pilu , i have wrote some test.

**Comment by milkwine** [comment]
I think this is not the right way to solve this problem after i have read some yaml specs.
so close this issuse.

**Comment by gravityblast** [comment]
@sawater thank you, I was also checking other libs and they do something else

**Pull request closed without merging**
